# ASSUMING US CUSTOMARY UNITS
LBS_TO_KIPS = 1 / 1000
KIPS_TO_LBS = 1000
POUNDS_TO_KIPS = 1 / 1000
KIPS_TO_POUNDS = 1000

FEET_TO_INCHES = 12
INCHES_TO_FEET = 1 / 12

__all__ = [
    "FEET_TO_INCHES",
    "INCHES_TO_FEET",
    "KIPS_TO_LBS",
    "KIPS_TO_POUNDS",
    "LBS_TO_KIPS",
    "POUNDS_TO_KIPS",
]
