from forallpeople import Physical

mm: Physical
ft: Physical
inch: Physical
N: Physical
kN: Physical
MN: Physical
Pa: Physical
kPa: Physical
MPa: Physical
GPa: Physical
Nm: Physical
N_m: Physical
lbft: Physical
kipft: Physical
psf: Physical
lbin: Physical
kipin: Physical
ksf: Physical
lb: Physical
lb_ft: Physical
plf: Physical
lb_in: Physical
pli: Physical
kip_ft: Physical
klf: Physical
kip_in: Physical
kli: Physical
kip: Physical
lbm: Physical
psi: Physical
ksi: Physical
pcf: Physical
kcf: Physical
pci: Physical
kci: Physical
N_m3: Physical
Nm2: Physical
lbft2: Physical
lbin2: Physical
kft2: Physical
kin2: Physical
J: Physical
MJ: Physical
W: Physical
sec: Physical
minute: Physical
hour: Physical
day: Physical
g: Physical
