[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "structural_tools"
version = "0.1.0"
description = "Structural engineering design and analysis tools"
requires-python = ">=3.14"

dependencies = [
    "handcalcs",
    "forallpeople",
    "ipython",
    "matplotlib",
    "mypy",
    "nbformat",
    "numpy",
    "pandas",
    "PyniteFEA[all]",
    "pyyaml",
    "ruff",
    "steelpy"
]

[project.scripts]
export-notebook = "structural_tools.scripts.export_notebook:main"
export-nb = "structural_tools.scripts.export_notebook:main"
remove-aux-files = "structural_tools.scripts.remove_aux_files:main"
banish-aux-files-to-the-shadow-dimension-where-they-belong = "structural_tools.scripts.remove_aux_files:main"
trim-image-whitespace = "structural_tools.scripts.trim_image_whitespace:main"
generate-shapes-js = "structural_tools.scripts.generate_shapes:main"

[tool.ruff]
line-length = 120