"""Generate shapes.js for the browser LTB calculator from steelpy.

The Python side reads steelpy live (see steel.database.get_section); the browser
can't, so this emits a static JS object with the same fundamental properties.
Re-run whenever you bump the steelpy / AISC database version.

Register in pyproject [project.scripts]:
    generate-shapes-js = "structural_tools.scripts.generate_shapes:main"
"""

import argparse
import sys
import time
from pathlib import Path

from steelpy import aisc

_COLLECTIONS = [
    ("W_shapes", "i_shape"),
    ("M_shapes", "i_shape"),
    ("S_shapes", "i_shape"),
    ("HP_shapes", "i_shape"),
    ("C_shapes", "channel"),
    ("MC_shapes", "channel"),
]
_PROPS = ["Zx", "Sx", "Iy", "Cw", "ry", "J", "ho"]

# Module-level flag toggled by --quiet; progress goes to stderr.
_QUIET = False


def _log(message: str) -> None:
    """Print a progress message to stderr unless --quiet is set."""
    if not _QUIET:
        print(message, file=sys.stderr, flush=True)


def _find_repo_root(start: Path) -> Path:
    for parent in (start, *start.parents):
        if (parent / "pyproject.toml").is_file():
            return parent
    return Path.cwd()


def _default_js_out() -> Path:
    return _find_repo_root(Path(__file__).resolve()) / "web" / "ltb" / "shapes.js"


def _iter_profiles(collection):
    """Yield Section objects from a steelpy collection (version-tolerant)."""
    try:
        yield from iter(collection)
    except TypeError:
        store = getattr(collection, "_sections", None) or getattr(collection, "sections", {})
        yield from store.values()


def _num(value: float) -> str:
    f = float(value)
    return str(int(f)) if f == int(f) else repr(round(f, 6))


def collect() -> dict[str, dict]:
    shapes: dict[str, dict] = {}
    total_skipped = 0

    _log(f"Reading {len(_COLLECTIONS)} shape collections from steelpy...")
    for attr, section_type in _COLLECTIONS:
        collection = getattr(aisc, attr)
        added = skipped = 0
        for prof in _iter_profiles(collection):
            label = str(getattr(prof, "name", "")).upper().strip()
            if not label:
                skipped += 1
                continue
            try:
                values = {p: float(getattr(prof, p)) for p in _PROPS}
            except AttributeError, TypeError, ValueError:
                skipped += 1
                continue
            values["type"] = section_type
            shapes[label] = values
            added += 1

        total_skipped += skipped
        note = f"  {attr:<10} → {added:>4} shapes"
        if skipped:
            note += f"  ({skipped} skipped, missing properties)"
        _log(note)

    _log(f"Collected {len(shapes)} shapes total" + (f" ({total_skipped} skipped)" if total_skipped else ""))
    return shapes


def render_js(shapes: dict[str, dict]) -> str:
    _log("Rendering JavaScript...")
    lines = [
        "// AUTO-GENERATED by scripts/generate_shapes.py from steelpy — do not edit.",
        "// AISC Shapes Database (kip-inch). r_ts and c are derived in-browser.",
        "const SHAPES = {",
    ]
    for name, d in shapes.items():
        lines.append(
            f'  "{name}": {{Zx:{_num(d["Zx"])}, Sx:{_num(d["Sx"])}, '
            f"Iy:{_num(d['Iy'])}, Cw:{_num(d['Cw'])}, ry:{_num(d['ry'])}, "
            f'J:{_num(d["J"])}, ho:{_num(d["ho"])}, type:"{d["type"]}"}},'
        )
    lines += ["};", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    global _QUIET

    parser = argparse.ArgumentParser(description="Generate shapes.js from steelpy.")
    parser.add_argument(
        "--js-out",
        default=None,
        help="Output path for shapes.js (default: <repo-root>/web/ltb/shapes.js)",
    )
    parser.add_argument("--quiet", action="store_true", help="Suppress progress messages.")
    args = parser.parse_args(argv)
    _QUIET = args.quiet

    start = time.perf_counter()
    out = Path(args.js_out) if args.js_out else _default_js_out()
    _log(f"Output target: {out}")

    shapes = collect()
    if not shapes:
        raise SystemExit("No shapes collected — check steelpy install/version.")

    js = render_js(shapes)

    out.parent.mkdir(parents=True, exist_ok=True)
    _log(f"Writing {len(js.encode('utf-8')):,} bytes to {out}...")
    out.write_text(js, encoding="utf-8")

    elapsed = time.perf_counter() - start
    _log(f"Done in {elapsed:.2f}s.")
    # Final summary on stdout (the one line a script might capture).
    print(f"Wrote {len(shapes)} shapes → {out}")


if __name__ == "__main__":
    main()
